// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateDescriptionInput struct {
	Point string `json:"point"`
}

type CreateInvestmentInput struct {
	Amount    float64 `json:"amount"`
	Timestamp *string `json:"timestamp,omitempty"`
}

type CreatePlanInput struct {
	Title        string                    `json:"title"`
	Amount       string                    `json:"amount"`
	Return       string                    `json:"return"`
	Duration     string                    `json:"duration"`
	ReferalBonus string                    `json:"referalBonus"`
	Description  []*CreateDescriptionInput `json:"description,omitempty"`
}

type CreateUserInput struct {
	UserImage *string `json:"userImage,omitempty"`
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	Email     *string `json:"email,omitempty"`
	Wallet    *string `json:"wallet,omitempty"`
	Phone     *string `json:"phone,omitempty"`
	Password  *string `json:"password,omitempty"`
	City      *string `json:"city,omitempty"`
	Country   *string `json:"country,omitempty"`
	Type      *string `json:"type,omitempty"`
}

type CreateWithdrawalRequestInput struct {
	Userid    string  `json:"userid"`
	From      *string `json:"from,omitempty"`
	Amount    float64 `json:"amount"`
	Timestamp *string `json:"timestamp,omitempty"`
}

type EditWalletInput struct {
	WalletID *string `json:"walletID,omitempty"`
	Address  *string `json:"address,omitempty"`
}

type MakeTransfer struct {
	From   *string  `json:"from,omitempty"`
	To     *string  `json:"to,omitempty"`
	Amount *float64 `json:"amount,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type UpdatePlanInput struct {
	Title        *string                   `json:"title,omitempty"`
	Amount       *string                   `json:"amount,omitempty"`
	Return       *string                   `json:"return,omitempty"`
	Duration     *string                   `json:"duration,omitempty"`
	ReferalBonus *string                   `json:"referalBonus,omitempty"`
	Description  []*CreateDescriptionInput `json:"description,omitempty"`
}
